In [24]:
import pandas as pd
import numpy as np
from sklearn.externals import joblib
from utils.classifications_utils import *
from utils.data_processing_utils import *
from utils.data_visualization_utils import *
from utils.metrics_utils import *
from utils.grid_search_utils import *
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier, AdaBoostClassifier
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

# Accelerometer

In [25]:
df_acc = pd.read_csv("acc_transformed_3_min.csv", index_col=0)
X_acc = df_acc.iloc[:, :-1]
y_acc = df_acc["label"]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X_acc, y_acc, test_size=0.2, random_state=42)

In [27]:
y_pred = np.random.random_integers(0, 5, size=(len(y_test), ))
accuracy_score(y_pred, y_test)

0.16028574617702868

In [28]:
get_confusion_matrix(y_pred, y_test)

             actual_0  actual_1  actual_2  actual_3  actual_4
predicted_0       573       636       581       625       582
predicted_1       605       561       643       578       571
predicted_2       610       609       554       609       571
predicted_3       600       566       600       568       589
predicted_4       601       636       656       627       616

# Stabilizer

In [29]:
df_sta = pd.read_csv("sta_transformed_3_min.csv", index_col=0)
X_sta = df_sta.iloc[:, :-1]
y_sta = df_sta["label"]
print("Stabilizer: " + str(df_sta.shape[0]))

Stabilizer: 89586

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X_sta, y_sta, test_size=0.2, random_state=42)

In [31]:
y_pred = np.random.random_integers(0, 5, size=(len(y_test), ))
accuracy_score(y_pred, y_test)

0.1662573947985266

In [32]:
get_confusion_matrix(y_pred, y_test)

             actual_0  actual_1  actual_2  actual_3  actual_4
predicted_0       584       607       606       610       576
predicted_1       594       587       620       585       563
predicted_2       623       619       609       573       558
predicted_3       627       616       590       592       631
predicted_4       543       578       605       602       607

# Gyro

In [33]:
df_gyro = pd.read_csv("gyro_transformed_3_min.csv", index_col=0)
X_gyro = df_gyro.iloc[:, :-1]
y_gyro = df_gyro["label"]
print("Accelerometer: " + str(df_gyro.shape[0]))

Accelerometer: 89586

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X_gyro, y_gyro, test_size=0.2, random_state=42)

In [35]:
y_pred = np.random.random_integers(0, 5, size=(len(y_test), ))
accuracy_score(y_pred, y_test)

0.164694720392901

In [36]:
get_confusion_matrix(y_pred, y_test)

             actual_0  actual_1  actual_2  actual_3  actual_4
predicted_0       553       567       667       638       556
predicted_1       604       632       606       595       632
predicted_2       604       600       618       608       579
predicted_3       591       606       614       569       580
predicted_4       613       571       581       606       579

# Gyro + Accelerometer

In [37]:
X_gyro_acc = pd.concat([X_gyro, X_acc], axis=1)
y_gyro_acc = y_gyro
X_gyro_acc.head()

,mu_x_gyro,mu_y_gyro,mu_z_gyro,std_x_gyro,std_y_gyro,std_z_gyro,avg_resultant_acc_gyro,bins_0_gyro,bins_1_gyro,bins_2_gyro,...,bins_23_acc,bins_24_acc,bins_25_acc,bins_26_acc,bins_27_acc,bins_28_acc,bins_29_acc,mean_average_difference_x_acc,mean_average_difference_y_acc,mean_average_difference_z_acc
0,0.423966,0.689068,0.143795,5.258876,5.135687,1.607270,6.642985,2.0,3.0,5.0,...,7.0,17.0,22.0,16.0,15.0,5.0,2.0,0.287634,0.210639,0.063305
1,0.409638,0.708761,0.134244,5.258213,5.137686,1.603247,6.646277,2.0,3.0,5.0,...,7.0,17.0,22.0,16.0,15.0,5.0,2.0,0.283445,0.211025,0.063272
2,0.338286,0.776274,0.120260,5.244151,5.222750,1.613862,6.692912,2.0,3.0,5.0,...,7.0,17.0,22.0,16.0,15.0,5.0,2.0,0.282941,0.208936,0.063698
3,0.238611,0.802374,0.093104,5.234158,5.215794,1.602169,6.671035,2.0,3.0,5.0,...,6.0,17.0,22.0,16.0,15.0,5.0,2.0,0.281943,0.199781,0.063799
4,0.141042,0.821388,0.069367,5.263072,5.233489,1.610829,6.704195,2.0,3.0,6.0,...,7.0,16.0,22.0,16.0,15.0,5.0,2.0,0.282471,0.198947,0.064390

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X_gyro_acc, y_gyro_acc, test_size=0.2, random_state=42)

In [39]:
y_pred = np.random.random_integers(0, 5, size=(len(y_test), ))
accuracy_score(y_pred, y_test)

0.16151356178144882

In [40]:
get_confusion_matrix(y_pred, y_test)

             actual_0  actual_1  actual_2  actual_3  actual_4
predicted_0       565       604       633       626       626
predicted_1       621       612       590       584       583
predicted_2       595       625       595       606       595
predicted_3       591       607       599       567       597
predicted_4       577       573       596       625       555

# Gyro + Stabilizer

In [41]:
X_gyro_sta = pd.concat([X_gyro, X_sta], axis=1)
y_gyro_sta = y_gyro
X_gyro_sta.head()

,mu_x_gyro,mu_y_gyro,mu_z_gyro,std_x_gyro,std_y_gyro,std_z_gyro,avg_resultant_acc_gyro,bins_0_gyro,bins_1_gyro,bins_2_gyro,...,bins_23_stabilizer,bins_24_stabilizer,bins_25_stabilizer,bins_26_stabilizer,bins_27_stabilizer,bins_28_stabilizer,bins_29_stabilizer,mean_average_difference_x_stabilizer,mean_average_difference_y_stabilizer,mean_average_difference_z_stabilizer
0,0.423966,0.689068,0.143795,5.258876,5.135687,1.607270,6.642985,2.0,3.0,5.0,...,16.0,10.0,6.0,5.0,4.0,10.0,13.0,0.163400,0.310911,0.158776
1,0.409638,0.708761,0.134244,5.258213,5.137686,1.603247,6.646277,2.0,3.0,5.0,...,18.0,8.0,6.0,5.0,4.0,10.0,13.0,0.164636,0.311551,0.158030
2,0.338286,0.776274,0.120260,5.244151,5.222750,1.613862,6.692912,2.0,3.0,5.0,...,16.0,8.0,6.0,6.0,3.0,10.0,13.0,0.167053,0.312735,0.157362
3,0.238611,0.802374,0.093104,5.234158,5.215794,1.602169,6.671035,2.0,3.0,5.0,...,16.0,8.0,7.0,4.0,4.0,9.0,13.0,0.168144,0.313757,0.156745
4,0.141042,0.821388,0.069367,5.263072,5.233489,1.610829,6.704195,2.0,3.0,6.0,...,17.0,7.0,7.0,4.0,4.0,9.0,13.0,0.168950,0.314334,0.156337

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X_gyro_sta, y_gyro_sta, test_size=0.2, random_state=42)

In [43]:
y_pred = np.random.random_integers(0, 5, size=(len(y_test), ))
accuracy_score(y_pred, y_test)

0.1650295791941065

In [44]:
get_confusion_matrix(y_pred, y_test)

             actual_0  actual_1  actual_2  actual_3  actual_4
predicted_0       563       530       591       615       619
predicted_1       621       617       595       570       576
predicted_2       607       613       629       643       575
predicted_3       569       590       627       562       595
predicted_4       658       620       608       593       586

# Accelerometer + Stabilizer

In [45]:
X_acc_sta = pd.concat([X_acc, X_sta], axis=1)
y_acc_sta = y_gyro
X_acc_sta.head()

,mu_x_acc,mu_y_acc,mu_z_acc,std_x_acc,std_y_acc,std_z_acc,avg_resultant_acc_acc,bins_0_acc,bins_1_acc,bins_2_acc,...,bins_23_stabilizer,bins_24_stabilizer,bins_25_stabilizer,bins_26_stabilizer,bins_27_stabilizer,bins_28_stabilizer,bins_29_stabilizer,mean_average_difference_x_stabilizer,mean_average_difference_y_stabilizer,mean_average_difference_z_stabilizer
0,-0.509557,-0.279534,1.018882,0.346928,0.273213,0.079338,1.239601,1.0,4.0,7.0,...,16.0,10.0,6.0,5.0,4.0,10.0,13.0,0.163400,0.310911,0.158776
1,-0.501934,-0.278313,1.018911,0.343203,0.273325,0.079296,1.235087,1.0,4.0,6.0,...,18.0,8.0,6.0,5.0,4.0,10.0,13.0,0.164636,0.311551,0.158030
2,-0.498901,-0.276406,1.018525,0.343154,0.272539,0.079937,1.232710,1.0,4.0,6.0,...,16.0,8.0,6.0,6.0,3.0,10.0,13.0,0.167053,0.312735,0.157362
3,-0.491748,-0.267881,1.018433,0.343136,0.252441,0.080053,1.224862,1.0,4.0,6.0,...,16.0,8.0,7.0,4.0,4.0,9.0,13.0,0.168144,0.313757,0.156745
4,-0.485814,-0.267094,1.017896,0.344372,0.251208,0.080409,1.222093,1.0,4.0,6.0,...,17.0,7.0,7.0,4.0,4.0,9.0,13.0,0.168950,0.314334,0.156337

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X_acc_sta, y_acc_sta, test_size=0.2, random_state=42)

In [47]:
y_pred = np.random.random_integers(0, 5, size=(len(y_test), ))
accuracy_score(y_pred, y_test)

0.16999665141198794

In [48]:
get_confusion_matrix(y_pred, y_test)

             actual_0  actual_1  actual_2  actual_3  actual_4
predicted_0       589       564       608       602       589
predicted_1       589       606       621       625       551
predicted_2       590       610       643       602       639
predicted_3       629       582       561       592       531
predicted_4       581       600       605       581       616

# All

In [49]:
X_all = pd.concat([X_gyro, X_acc, X_sta], axis=1)
y_all = y_gyro
X_all.head()

,mu_x_gyro,mu_y_gyro,mu_z_gyro,std_x_gyro,std_y_gyro,std_z_gyro,avg_resultant_acc_gyro,bins_0_gyro,bins_1_gyro,bins_2_gyro,...,bins_23_stabilizer,bins_24_stabilizer,bins_25_stabilizer,bins_26_stabilizer,bins_27_stabilizer,bins_28_stabilizer,bins_29_stabilizer,mean_average_difference_x_stabilizer,mean_average_difference_y_stabilizer,mean_average_difference_z_stabilizer
0,0.423966,0.689068,0.143795,5.258876,5.135687,1.607270,6.642985,2.0,3.0,5.0,...,16.0,10.0,6.0,5.0,4.0,10.0,13.0,0.163400,0.310911,0.158776
1,0.409638,0.708761,0.134244,5.258213,5.137686,1.603247,6.646277,2.0,3.0,5.0,...,18.0,8.0,6.0,5.0,4.0,10.0,13.0,0.164636,0.311551,0.158030
2,0.338286,0.776274,0.120260,5.244151,5.222750,1.613862,6.692912,2.0,3.0,5.0,...,16.0,8.0,6.0,6.0,3.0,10.0,13.0,0.167053,0.312735,0.157362
3,0.238611,0.802374,0.093104,5.234158,5.215794,1.602169,6.671035,2.0,3.0,5.0,...,16.0,8.0,7.0,4.0,4.0,9.0,13.0,0.168144,0.313757,0.156745
4,0.141042,0.821388,0.069367,5.263072,5.233489,1.610829,6.704195,2.0,3.0,6.0,...,17.0,7.0,7.0,4.0,4.0,9.0,13.0,0.168950,0.314334,0.156337

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2, random_state=42)

In [51]:
y_pred = np.random.random_integers(0, 5, size=(len(y_test), ))
accuracy_score(y_pred, y_test)

0.1661457751981248

In [52]:
get_confusion_matrix(y_pred, y_test)

             actual_0  actual_1  actual_2  actual_3  actual_4
predicted_0       574       594       579       670       598
predicted_1       594       578       543       552       575
predicted_2       582       594       638       581       606
predicted_3       590       587       642       599       578
predicted_4       630       598       609       589       588